# analysis_options.yaml

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"

linter:
  rules:
    prefer_initializing_formals: false
    unnecessary_underscores: false
    unnecessary_brace_in_string_interps: false
    use_null_aware_elements: false
    prefer_const_constructors: false
    avoid_print: true
    always_declare_return_types: true
